#compose.yaml
version: '3.8'
services:
  app:
    image: malenekavanagh/main:latest
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "host.docker.internal:172.17.0.0"
    networks:
      - my_external_network
    #network dependency
  server:
    build:
      context: .
      target: final
    ports:
      - 80:80
    #port mapping
   #dependency on app service  
    depends_on:
      - app
    networks:
      - my_external_network

networks:
  my_external_network:
    name: bridge
    external: true
    #to get network access it uses the external bridge network
