name: Build and upload Docker image to cloud

'on':
  push:
    branches:
      - main
      
permissions:
  contents: read
  id-token: write
  
env:
  PROJECT_ID: myinterviewexercise
  REGION: us-west1
  SERVICE: github-work-service
  REPO: repo-main
  IMAGE: malenekavanagh/main
  GCS_KEY: '${{ secrets.GC_KEY_SERVICE }}'
  
jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
          
      - name: setting the variables
        run: >-
          echo "$IMAGE-TAG=$REGION-docker.pkg.dev/$Project/$REPO/$IMAGE" >> $GITHUB_ENV
          
      - name: Authenticating to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GC_KEY_SERVICE }}'

      - name: Setting up gcloud 
        uses: google-github-actions/setup-gcloud@v2
        
      - name: Docker authentication
        run: 'gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet'
        
      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_TAG }}
            ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO }}/${{ env.IMAGE }}:latest
               
      - name: Deploy to Cloud Run from Source
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.SERVICE }}
          region: ${{ env.REGION }}
          source: .
          
      - name: Show output URL
        run: 'echo ${{ steps.deploy.outputs.url }}'      

  liatrio-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: setting the variables
        run: >-
          echo "$IMAGE-TAG=$REGION-docker.pkg.dev/$Project/$REPO/$IMAGE" >> $GITHUB_ENV
        
      - name: Docker authentication
        run: 'gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet'
        
      - name: build image
        run: docker build -t malenekavanagh/main:latest -t malenekavanagh/main:${{ github.sha }} .

      - name: running on port 80
        run: docker run -d --name svc -p 80:80 malenekavanagh/main:${{ github.sha }} 
     
      - name: run tests
        uses: liatrio/github-actions/apprentice-action@0b41561cca6822cc8d880fe0e49e7807a41fdf91
